# Generated by Django 4.2 on 2024-07-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Condition_is_being_assessed',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='company',
            name='year_of_foundation',
            field=models.CharField(max_length=80),
        ),
    ]
