# Generated by Django 4.2 on 2024-07-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=70)),
                ('age', models.IntegerField(default=18)),
                ('photo', models.ImageField(upload_to='static/images')),
                ('email', models.EmailField(max_length=80)),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.cource')),
            ],
        ),
    ]
