# Generated by Django 4.2 on 2024-07-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='midle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тахаллус:'),
        ),
    ]
