# Generated by Django 4.2 on 2024-07-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
