# Generated by Django 4.2 on 2024-07-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(default=1, upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
