# Generated by Django 4.2 on 2024-07-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='date_of_issue',
            field=models.IntegerField(),
        ),
    ]
